manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: tee-nahan
      url-base: https://github.com/Tee-nahan
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: tee-nahan
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: tee-nahan
      revision: 94d3607529c5896b0f7e6099ed32fb72155f0298
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
